FROM node:16-alpine as build

WORKDIR /usr/src/app

# install app dependencies
COPY package*.json ./
RUN yarn

COPY . .

# start app
RUN chmod +x entrypoint.sh
RUN /usr/src/app/entrypoint.sh

FROM nginx:alpine as serve

COPY ./docker/default.conf /etc/nginx/conf.d/default.conf

COPY ./docker/certs /etc/nginx/certs/devpost-hackathon.xyz

COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
