FROM node:16-alpine as build

WORKDIR /usr/src/app

# install app dependencies
COPY package*.json ./
RUN npm install

COPY . .

# start app
RUN npm run build

FROM nginx:alpine as serve

COPY ./docker/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
