FROM nginx:latest

COPY default.conf /etc/nginx/conf.d/default.conf

COPY certs/fullchain.pem /etc/nginx/certs/devpost-hackathon.xyz/fullchain.pem
COPY certs/privkey.pem /etc/nginx/certs/devpost-hackathon.xyz/privkey.pem