FROM node:16-alpine as build

WORKDIR /usr/src/app

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --immutable --immutable-cache --check-cache

COPY . .

# start app
CMD ["yarn", "start"]
