FROM node:16-alpine as build

WORKDIR /usr/src/app

# install app dependencies
COPY package*.json ./
RUN yarn

COPY . .

# start app
RUN chmod +x entrypoint.sh
ENTRYPOINT "/usr/src/app/entrypoint.sh"
