FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/default.conf

COPY certs /etc/nginx/certs/devpost-hackathon.xyz

COPY build /usr/share/nginx/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]